FROM python:3.11

RUN pip install numpy

COPY . /app
WORKDIR /app
RUN python3 setup.py install
RUN pip install dkimpy
RUN pip install Flask-Cors

# Install Playwright and its dependencies
RUN pip install playwright
RUN python -m playwright install

# Install Chromium
RUN apt-get update && apt-get install -y wget gnupg
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
RUN apt-get update && apt-get install -y google-chrome-stable

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "app.py"]